server:
  port: 8081
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/