services:
  accountssvc:
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    container_name: accountscn
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    networks:
      - mor
  cardssvc:
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    container_name: cardscn
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardsdb
    networks:
      - mor
  loanssvc:
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    container_name: loanscn
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    networks:
      - mor

  eurekaserver:
    image: "mor22/eurekaserver:s8"
    container_name: eurekaserver-ms
    ports:
      - 8084:8084
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health | grep UP || exit 1"
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mor
  accounts:
    image: "mor22/accounts:s8"
    container_name: accounts-ms
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountssvc/accountsdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      accountssvc:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      - mor
  cards:
    image: "mor22/cards:s8"
    container_name: cards-ms
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardssvc/cardsdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      cardssvc:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      - mor
  loans:
    image: "mor22/loans:s8"
    container_name: loans-ms
    ports:
      - 8083:8083
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loanssvc/loansdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      loanssvc:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      - mor
networks:
  mor:
    driver: "bridge"