server:
  port: 8083
spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3309/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/